name: instagram_clone
description: "Instagram Clone Flutter Project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
     - family: InstagramSans
       fonts:
         - asset: fonts/Instagram-Sans.ttf
         - asset: fonts/Instagram-Sans-Bold.ttf
           weight: 700
         - asset: fonts/Instagram-Sans-Light.ttf
           weight: 300
         - asset: fonts/Instagram-Sans-Medium.ttf
           weight: 500
     - family: InstagramSansHeadline
       fonts:
         - asset: fonts/Instagram-Sans-Headline.otf
